
INSERT INTO orders VALUES (DEFAULT,'Vanilla','White','1/6 Sheet',1,'Red Frosting','Hamburger','Orange Message Color','None','Happy Birthday!',false,'Online','1442275200','9:00 AM',false,'Not Built','Kawika','Kekahuna','8089382031');
INSERT INTO orders VALUES (DEFAULT,'Chocolate','Chocolate','1/3 Sheet',1,'Blue Frosting','Hamburger','Orange Message Color','None','Happy Birthday!',false,'Online','1442275200','10:00 AM',false,'Not Built','Johnny','Tsunami','8089382031');
INSERT INTO orders VALUES (DEFAULT,'Very Berry Strawberry','Fudge Crunch','Full Sheet + 2/3',1,'Red Frosting','Hamburger','Orange Message Color','None','Happy Birthday!',false,'Online','1442275200','11:00 AM',false,'Not Built','Jeff','Lee','8089382031');
INSERT INTO orders VALUES (DEFAULT,'Rocky Road','White','2/3 Sheet',1,'Orange Frosting','Hamburger','Orange Message Color','None','Happy Birthday!',false,'Online','1442275200','12:00 AM',false,'Not Built','Corey','Kinata','8089382031');
INSERT INTO orders VALUES (DEFAULT,'Pistachio Almonds','Chocolat','1/3 Sheet',1,'Red Frosting','Hamburger','Orange Message Color','None','Happy Birthday!',false,'Online','1442275200','1:00 PM',false,'Not Built','Malia','Oreta','8089382031');
INSERT INTO orders VALUES (DEFAULT,'Jamoca','Fudge Crunch','Dome',1,'Purple Frosting','Hamburger','Orange Message Color','None','Happy Birthday!',false,'Online','1442275200','2:00 AM',false,'Not Built','Rex','Chun','8089382031');
INSERT INTO orders VALUES (DEFAULT,'Jamoca Almond Fudge','White','Full Sheet',1,'Yellow Frosting','Candy Crazy','Red Message Color','None','Happy Birthday!',false,'Online','1442275200','3:00 PM',false,'Not Built','Sean','Chun','8089382031');
INSERT INTO orders VALUES (DEFAULT,'Pralines & Cream','Chocolate','1/3 Sheet',1,'Black Frosting','Hamburger','Purple Message Color','None','Happy Birthday!',false,'Online','1442275200','5:00 PM',false,'Not Built','Jasmine','Something','8089382031');
INSERT INTO orders VALUES (DEFAULT,'Vanilla','Fudge Crunch','Full + 1/3 Sheet',1,'Violet Frosting','Clown','Blue Message Color','None','Happy Birthday!',false,'Online','1442275200','9:00 AM',false,'Not Built','Jamie','Somethin','8089382031');
INSERT INTO orders VALUES (DEFAULT,'Vanilla','White','2/3 Sheet',1,'Tiffany Blue Frosting','Hamburger','Light Blue Message Color','None','Happy Birthday!',false,'Online','1442275200','9:00 PM',false,'Not Built','Chad','Corey','8089382031');
INSERT INTO cake_sizes VALUES (DEFAULT,'1/6 Sheet');
INSERT INTO cake_sizes VALUES (DEFAULT,'1/3 Sheet');
INSERT INTO cake_sizes VALUES (DEFAULT,'1/2 Sheet');
INSERT INTO cake_sizes VALUES (DEFAULT,'2/3 Sheet');
INSERT INTO cake_sizes VALUES (DEFAULT,'Full Sheet');
INSERT INTO cake_sizes VALUES (DEFAULT,'Full + 1/3 Sheet');
INSERT INTO cake_sizes VALUES (DEFAULT,'Full + 1/2 Sheet');
INSERT INTO cake_sizes VALUES (DEFAULT,'Full + 2/3 Sheet');
INSERT INTO cake_sizes VALUES (DEFAULT,'Double-Full Sheet');
INSERT INTO cake_sizes VALUES (DEFAULT,'6" Round');
INSERT INTO cake_sizes VALUES (DEFAULT,'9" Round');
INSERT INTO cake_sizes VALUES (DEFAULT,'Dome');
INSERT INTO cake_sizes VALUES (DEFAULT,'Cupcake-Cake');
INSERT INTO cake_sizes VALUES (DEFAULT,'Roll');
INSERT INTO cake_sizes VALUES (DEFAULT,'Decoration Pack');
INSERT INTO cake_flavors VALUES (DEFAULT,'White');
INSERT INTO cake_flavors VALUES (DEFAULT,'Chocolate');
INSERT INTO cake_flavors VALUES (DEFAULT,'Fudge Crunch');
INSERT INTO icecream_flavors VALUES (DEFAULT,'Oreo Cookies & Cream');
INSERT INTO icecream_flavors VALUES (DEFAULT,'Chocolate Chip Cookie Dough');
INSERT INTO icecream_flavors VALUES (DEFAULT,'Made With Snickers');
INSERT INTO icecream_flavors VALUES (DEFAULT,'Pistachio Almond');
INSERT INTO icecream_flavors VALUES (DEFAULT,'Rocky Road');
INSERT INTO icecream_flavors VALUES (DEFAULT,'Chocolate');
INSERT INTO icecream_flavors VALUES (DEFAULT,'Jamoca');
INSERT INTO icecream_flavors VALUES (DEFAULT,'Mint Chocolate Chip');
INSERT INTO icecream_flavors VALUES (DEFAULT,'Pralines n Cream');
INSERT INTO icecream_flavors VALUES (DEFAULT,'Vanilla');
INSERT INTO icecream_flavors VALUES (DEFAULT,'Chocolate Chip');
INSERT INTO icecream_flavors VALUES (DEFAULT,'Jamoca Almond Fudge');
INSERT INTO icecream_flavors VALUES (DEFAULT,'Peanut Butter & Chocolate');
INSERT INTO icecream_flavors VALUES (DEFAULT,'Reeses Peanut Butter Cup');
INSERT INTO icecream_flavors VALUES (DEFAULT,'Very Bery Strawberry');
INSERT INTO message_colors VALUES (DEFAULT,'Red');
INSERT INTO message_colors VALUES (DEFAULT,'Blue');
INSERT INTO message_colors VALUES (DEFAULT,'Orange');
INSERT INTO message_colors VALUES (DEFAULT,'White');
INSERT INTO message_colors VALUES (DEFAULT,'Brown');
INSERT INTO message_colors VALUES (DEFAULT,'Green');
INSERT INTO message_colors VALUES (DEFAULT,'Yellow');
INSERT INTO message_colors VALUES (DEFAULT,'Black');
INSERT INTO message_colors VALUES (DEFAULT,'Purple');
INSERT INTO preset_messages VALUES (DEFAULT,'Happy Birthday');
INSERT INTO preset_messages VALUES (DEFAULT,'Congratulations');
INSERT INTO preset_messages VALUES (DEFAULT,'Happy Graduation');
INSERT INTO preset_messages VALUES (DEFAULT,'I love you');
INSERT INTO preset_messages VALUES (DEFAULT,'Happy Mothers Day');
INSERT INTO preset_messages VALUES (DEFAULT,'Happy Fathers Day');
INSERT INTO preset_messages VALUES (DEFAULT,'Just Because!');
INSERT INTO quantity VALUES (DEFAULT,'1');
INSERT INTO quantity VALUES (DEFAULT,'2');
INSERT INTO quantity VALUES (DEFAULT,'3');
