INSERT INTO flavors VALUES (DEFAULT,'Oreo Cookies & Cream',false,false);
INSERT INTO flavors VALUES (DEFAULT,'Chocolate Chip Cookie Dough',false,false);
INSERT INTO flavors VALUES (DEFAULT,'Made With Snickers',false,false);
INSERT INTO flavors VALUES (DEFAULT,'Pistachio Almond',false,false);
INSERT INTO flavors VALUES (DEFAULT,'Rocky Road',false,false);
INSERT INTO flavors VALUES (DEFAULT,'Chocolate',false,false);
INSERT INTO flavors VALUES (DEFAULT,'Jamoca',false,false);
INSERT INTO flavors VALUES (DEFAULT,'Mint Chocolate Chip',false,false);
INSERT INTO flavors VALUES (DEFAULT,'Pralines n Cream',false,false);
INSERT INTO flavors VALUES (DEFAULT,'Vanilla',false,false);
INSERT INTO flavors VALUES (DEFAULT,'Chocolate Chip',false,false);
INSERT INTO flavors VALUES (DEFAULT,'Jamoca Almond Fudge',false,false);
INSERT INTO flavors VALUES (DEFAULT,'Peanut Butter & Chocolate',false,false);
INSERT INTO flavors VALUES (DEFAULT,'Reeses Peanut Butter Cup',false,false);
INSERT INTO flavors VALUES (DEFAULT,'Very Bery Strawberry',false,false);
